#!/bin/bash
# 
ps -eaf | grep play | grep envoy > /dev/null
if [ $? -ne 0 ]; then
  rm /opt/envoy_ws/target/universal/stage/RUNNING_PID
fi
/opt/envoy_ws/target/universal/stage/bin/envoy_ws -D-Xmx512m -Dhttp.port=9001 -Djava.awt.headless=true  &


